{{ if not .Values.hvpa.enabled }}
{{- /* .Values.replicas is of type 'float64', so let's cast it to string to have proper types for comparison */}}
{{- if ne (.Values.replicas | toString) "0" }}
apiVersion: {{ include "hpaversion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: controlplane
    app: kubernetes
    role: apiserver
spec:
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  scaleTargetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: kube-apiserver
  metrics:
  {{- if not .Values.hpa.customMetrics.enabled }}
  - type: Resource
    resource:
      name: cpu
      type:
      targetAverageUtilization: {{ .Values.hpa.targetAverageUtilizationCpu }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.hpa.targetAverageUtilizationMemory }}
  {{- else }}
  {{- .Values.hpa.customMetrics.metrics | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
{{ end }}
