replicas: 1
kubernetesVersion: 1.15.2
priorityClassName: foo
securePort: 443
konnectivityTunnel:
  enabled: false
  serverPort: 0
  agentPort: 8132
  adminPort: 8133
  healthPort: 8134
  agentNamespace: kube-system
probeCredentials: base64(user:pass)
shootNetworks:
  services: 10.0.1.0/24
  pods: 192.168.0.0/1
# nodes: 172.16.0.0/20
podAnnotations: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
runtimeConfig: {}
  # autoscaling/v2alpha1: true

oidcConfig: {}
  # caBundle: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # clientID: clientid
  # groupsClaim: groups
  # groupsPrefix: prefix
  # issuerURL: http://localhost
  # signingAlgs:
  # - foo
  # requiredClaims:
  #   foo: bar
  #   bar: foo
  # usernameClaim: user
  # usernamePrefix: prefix

admissionPlugins:
- name: Priority
- name: NamespaceLifecycle
- name: LimitRanger
- name: PodSecurityPolicy
- name: ServiceAccount
- name: NodeRestriction
- name: DefaultStorageClass
- name: PersistentVolumeLabel
- name: DefaultTolerationSeconds
- name: StorageObjectInUseProtection
- name: MutatingAdmissionWebhook
- name: ValidatingAdmissionWebhook
- name: ResourceQuota
# - name: PodNodeSelector
#   config:
#     podNodeSelectorPluginConfig:
#       clusterDefaultNodeSelector: <node-selectors-labels>
#       namespace1: <node-selectors-labels>
#       namespace2: <node-selectors-labels>

images:
  kube-apiserver: image-repository
  vpn-seed: image-repository:image-tag
  konnectivity-server: image-repository:image-tag
  apiserver-proxy-pod-webhook: image-repository:image-tag

blackboxExporterPort: 9115
etcdServicePort: 2379

vpnSeedResources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1000M

apiServerResources:
  requests:
    cpu: 400m
    memory: 400M
  limits:
    cpu: 800m
    memory: 900M

konnectivityTunnelResources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 500M

podMutatorResources:
  requests:
    cpu: 50m
    memory: 128M
  limits:
    cpu: 200m
    memory: 500M

maxReplicas: 1
minReplicas: 1

hpa:
  customMetrics:
    enabled: false
    metrics:
    - type: Pods
      pods:
        metricName: requests_per_second
        targetAverageValue: 100
    - type: Pods
      pods:
        metricName: current_inflight_requests
        targetAverageValue: 50
  targetAverageUtilizationCpu: 80
  memoryMetricForHpaEnabled: false
  targetAverageUtilizationMemory: 80

vpa:
  updateMode: "Off"

auditConfig:
  auditPolicy: ""

enableEtcdEncryption: false
enableBasicAuthentication: true

## Identifiers of the API. The service account token authenticator will validate that tokens used
## against the API are bound to at least one of these audiences. If the .serviceAccountConfig.issuer
## is configured and this flag is not, this field defaults to a single element list
## containing the issuer URL .
apiAudiences:
- kubernetes

## Configuration of how to issue service accounts
#serviceAccountConfig:
#  # Identifier of the service account token issuer. The issuer will assert this identifier in "iss"
#  # claim of issued tokens. This value is a string or URI.
#  issuer: "my-issuer"
#  # The current private key of the service account token issuer. The issuer will sign issued ID
#  #  tokens with this private key. (Requires the 'TokenRequest' feature gate.)
#  signingKey: <private key in PEM format>

hvpa:
  enabled: false

scaleUpStabilization:
  stabilizationDuration: "3m"
  minChange:
    cpu:
      value: 300m
      percentage: 80
    memory:
      value: 200M
      percentage: 80

scaleDownStabilization:
  stabilizationDuration: "15m"
  minChange:
    cpu:
      value: 300m
      percentage: 80
    memory:
      value: 200M
      percentage: 80
scaleDownUpdateMode: "Auto"

limitsRequestsGapScaleParams:
  cpu:
    value: "1"
    percentage: 70
  memory:
    value: "1G"
    percentage: 70

sni:
  enabled: false
  advertiseIP: 1.1.1.1
  podMutatorEnabled: false
  # apiserverFQDN: foo.bar.

mountHostCADirectories:
  enabled: false

# watchCacheSizes:
#   default: 100
#   resources:
#     - resource: secrets
#       size: 500
#     - apiGroup: apps
#       resource: deployments
#       size: 500

#maxNonMutatingRequestsInflight: 400
#maxMutatingRequestsInflight: 200

reversedVPN:
  enabled: false
