name: verify

on:
  pull_request:
    branches: [ master, release-* ]

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v2.17.0
    - name: Go Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/bin
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Configure Git
      run: |
        git config --global user.email "gardener@sap.com"
        git config --global user.name "Gardener CI/CD"

    - run: make install-requirements
    - run: sudo ./hack/install-protobuf.sh # installs protoc to /usr/local/bin -> needs sudo
    - run: make check-generate
    - run: make check
    - run: make format
    - run: make test-cov

    - name: Coverprofile artifacts
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: test.coverage.html
